#!/usr/bin/env bash

CD=$(brew --cache)
HD=~/
UD=/usr/local/var/dotfiles

case "${1}" in
  install)
    while (( "$#" )); do
      case "${2}" in
        --overwrite) OVERWRITE='0' ; shift ;;
        --silent) SILENT='0' ; shift ;;
        --username=*) USERNAME=${2/--username=/''} ; shift ;;
        -o) OVERWRITE='0' ; shift ;;
        -s) SILENT='0' ; shift ;;
        -u*) USERNAME=${3} ; shift ; shift ;;
        *) test -n "${2}" && USERNAME=${2} ; shift ;;
      esac
    done

    test -z "${USERNAME}" && read -e -p 'Enter username (e.g. rockymadden): ' USERNAME

    ${0} uninstall --silent
    mkdir -p "${CD}/Dotfiles"
    mkdir -p "${UD}"

    test -z "${SILENT}" && echo -n 'Downloading: '
    curl -f -L -s -o "${CD}/Dotfiles/${USERNAME}-master.tar.gz" "https://github.com/${USERNAME}/dotfiles/archive/master.tar.gz"
    case "$?" in
      0) test -z "${SILENT}" && echo 'done' ;;
      *) test -z "${SILENT}" && echo 'fail' ; exit 1 ;;
    esac

    test -z "${SILENT}" && echo -n 'Decompressing: '
    tar -x -f "${CD}/Dotfiles/${USERNAME}-master.tar.gz" -C "${UD}" --strip 1
    case "$?" in
      0) test -z "${SILENT}" && echo 'done' ;;
      *) test -z "${SILENT}" && echo 'fail' ; exit 1 ;;
    esac

    test -z "${SILENT}" && echo -n 'Securing: '
    chmod -R g-rwx "${UD}" && chmod -R o-rwx "${UD}"
    case "$?" in
      0) test -z "${SILENT}" && echo 'done' ;;
      *) test -z "${SILENT}" && echo 'fail' ; exit 1 ;;
    esac

    test -z "${SILENT}" && echo -n 'Stubbing dotfile directories: '
    find "${UD}" -type d | tail -n +2 | sed "s|${UD}|${HD}|" | xargs -I{} mkdir -p {}
    case "$?" in
      0) test -z "${SILENT}" && echo 'done' ;;
      *) test -z "${SILENT}" && echo 'fail' ; exit 1 ;;
    esac

    test -z "${SILENT}" && echo -n 'Symlinking dotfile files: '
    test -n "${OVERWRITE}" && find "${UD}" -type f ! -name '.DS_Store' | sed "s|${UD}|${HD}|" | xargs -I{} rm -f {}
    find "${UD}" -type f ! -name '.DS_Store' | sed "s|${UD}||" | xargs -I{} ln -s ${UD}{} ${HD}{}
    case "$?" in
      0) test -z "${SILENT}" && echo 'done' ;;
      *) test -z "${SILENT}" && echo 'fail' ; exit 1 ;;
    esac
  ;;

  uninstall)
    while (( "$#" )); do
      case "${2}" in
        --silent) SILENT='0' ; shift ;;
        -s) SILENT='0' ; shift ;;
        *) shift ;;
      esac
    done

    test -z "${SILENT}" && echo -n 'Uninstalling: '
    rm -rf "${UD}" && \
    find "${HD}" -type l -ls | grep "${UD}" | awk '{print $11}' | sed 's|//|/|' | xargs -I{} rm -f {}
    case "$?" in
      0) test -z "${SILENT}" && echo 'done' ;;
      *) test -z "${SILENT}" && echo 'fail' ; exit 1 ;;
    esac
  ;;

  --help)
    echo 'Usage:'
    echo "  brew dotfiles install <username> [--overwrite|-o] [--silent|-s]"
    echo "  brew dotfiles uninstall [--silent|-s]"
    echo
    echo "Commands:"
    echo "  install       Install dotfiles corresponding to username/dotfiles"
    echo "  uninstall     Uninstall dotfiles"
  ;;

  *) ${0} --help ; exit 1 ;;
esac

exit 0
